package com.apixDrive;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.regex.Pattern;
import java.util.concurrent.TimeUnit;
import org.junit.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;


public class LoginTest {

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/drivers/chromedriver.exe");

        driver = new ChromeDriver();
    }

    public ChromeDriver driver;

    @Test
    public void firstTest() {
        driver.get("https://apix-drive.com/ru");
        driver.findElement(By.linkText("Вход")).click();
        driver.findElement(By.name("login")).click();
        driver.findElement(By.name("login")).clear();
        driver.findElement(By.name("login")).sendKeys("alextesting23@gmail.com");
        driver.findElement(By.name("pass")).clear();
        driver.findElement(By.name("pass")).sendKeys("123456gg");
        driver.findElement(By.xpath("//input[@value='Вход']")).click();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.findElement(By.id("user_menu")).click();
        driver.findElement(By.linkText("Выход")).click();
    }

    @Test
    public void testCountryRU() throws Exception {
        driver.get("https://apix-drive.com/ru");
        driver.findElement(By.xpath("//div[@id='main_site_header']/div/div/div[3]/div")).click();
        driver.findElement(By.xpath("(//a[contains(text(),'RU')])[2]")).click();
    }

    @Test
    public void testCountryUA() throws Exception {
        driver.get("https://apix-drive.com/ru");
        driver.findElement(By.xpath("//div[@id='main_site_header']/div/div/div[3]/div")).click();
        driver.findElement(By.xpath("(//a[contains(text(),'UA')])[2]")).click();
    }

    @Test
    public void testAllHelp22052021() throws Exception {
        driver.manage().window().setPosition(new Point(0,0));
        driver.manage().window().setSize(new Dimension(1024,768));
        driver.get("https://apix-drive.com/ru");
        driver.findElement(By.linkText("Справка")).click();
        driver.findElement(By.linkText("1. Принцип работы")).click();
        driver.findElement(By.linkText("2. Главный экран")).click();
        driver.findElement(By.linkText("1. Главное Меню")).click();
        driver.findElement(By.linkText("2. Связи")).click();
        driver.findElement(By.linkText("3. Настройки связей")).click();
        driver.findElement(By.linkText("4. Автообновление")).click();
        driver.findElement(By.linkText("5. Удаление связей")).click();
        driver.findElement(By.linkText("6. Удаление аккаунтов")).click();
        driver.findElement(By.linkText("7. Профиль и пароль")).click();
        driver.findElement(By.linkText("3. Создание связи")).click();
        driver.findElement(By.linkText("1. Добавление источника данных")).click();
        driver.findElement(By.linkText("2. Добавление приема данных")).click();
        driver.findElement(By.linkText("3. Навигация")).click();
        driver.findElement(By.linkText("4. ИСТОЧНИКИ данных")).click();
        driver.findElement(By.linkText("Active Chat")).click();
        driver.findElement(By.linkText("ActiveCampaign")).click();
        driver.findElement(By.linkText("Admitad")).click();
        driver.findElement(By.linkText("AgileCRM")).click();
        driver.findElement(By.linkText("Aimylogic")).click();
        driver.findElement(By.linkText("Alloka")).click();
        driver.findElement(By.linkText("AmoCRM")).click();
        driver.findElement(By.linkText("AOL")).click();
        driver.findElement(By.linkText("Asana")).click();
        driver.findElement(By.linkText("BigQuery")).click();
        driver.findElement(By.linkText("Binotel")).click();
        driver.findElement(By.linkText("Bloxy")).click();
        driver.findElement(By.linkText("BotHelp")).click();
        driver.findElement(By.linkText("Botmother")).click();
        driver.findElement(By.linkText("Bpium")).click();
        driver.findElement(By.linkText("CallBackHunter")).click();
        driver.findElement(By.linkText("Callcpa")).click();
        driver.findElement(By.linkText("Callibri")).click();
        driver.findElement(By.linkText("CallKeeper")).click();
        driver.findElement(By.linkText("CallTouch")).click();
        driver.findElement(By.linkText("CallTracking")).click();
        driver.findElement(By.linkText("Carrot quest")).click();
        driver.findElement(By.linkText("CartProtector")).click();
        driver.findElement(By.linkText("ChatForma")).click();
        driver.findElement(By.linkText("Chatfuel")).click();
        driver.findElement(By.linkText("Chatra")).click();
        driver.findElement(By.linkText("Contact Form 7")).click();
        driver.findElement(By.linkText("Copper")).click();
        driver.findElement(By.linkText("Creatio")).click();
        driver.findElement(By.linkText("Criteo")).click();
        driver.findElement(By.linkText("CS-Cart")).click();
        driver.findElement(By.linkText("E-Autopay")).click();
        driver.findElement(By.linkText("Ecwid")).click();
        driver.findElement(By.linkText("Enquiz")).click();
        driver.findElement(By.linkText("Envybox")).click();
        driver.findElement(By.linkText("EnvyCRM")).click();
        driver.findElement(By.linkText("Facebook")).click();
        driver.findElement(By.linkText("Flexbe")).click();
        driver.findElement(By.linkText("FlowXO")).click();
        driver.findElement(By.linkText("Fondy")).click();
        driver.findElement(By.linkText("FormDesigner")).click();
        driver.findElement(By.linkText("FreshOffice")).click();
        driver.findElement(By.linkText("GetCourse")).click();
        driver.findElement(By.linkText("Gmail")).click();
        driver.findElement(By.linkText("Google Ads")).click();
        driver.findElement(By.linkText("Google Analytics")).click();
        driver.findElement(By.linkText("Google Calendar")).click();
        driver.findElement(By.linkText("Google Contacts")).click();
        driver.findElement(By.linkText("Google Lead Form")).click();
        driver.findElement(By.linkText("Google Sheets")).click();
        driver.findElement(By.linkText("Horoshop")).click();
        driver.findElement(By.linkText("HotLine")).click();
        driver.findElement(By.linkText("Hubspot")).click();
        driver.findElement(By.linkText("iCloud")).click();
        driver.findElement(By.linkText("IMAP")).click();
        driver.findElement(By.linkText("INBOX.LV")).click();
        driver.findElement(By.linkText("Infobot")).click();
        driver.findElement(By.linkText("InSales")).click();
        driver.findElement(By.linkText("Intrum")).click();
        driver.findElement(By.linkText("Jira Service Desk")).click();
        driver.findElement(By.linkText("Jira Software Cloud")).click();
        driver.findElement(By.linkText("JivoSite")).click();
        driver.findElement(By.linkText("JustClick")).click();
        driver.findElement(By.linkText("Justin")).click();
        driver.findElement(By.linkText("Klientiks")).click();
        driver.findElement(By.linkText("Lamoda")).click();
        driver.findElement(By.linkText("Landingi")).click();
        driver.findElement(By.linkText("LeadBack")).click();
        driver.findElement(By.linkText("LeadForms")).click();
        driver.findElement(By.linkText("LeadPlan")).click();
        driver.findElement(By.linkText("Leeloo")).click();
        driver.findElement(By.linkText("LiqPay")).click();
        driver.findElement(By.linkText("LiveChat")).click();
        driver.findElement(By.linkText("Livetex")).click();
        driver.findElement(By.linkText("Lp-CRM")).click();
        driver.findElement(By.linkText("LPGenerator")).click();
        driver.findElement(By.linkText("LPMotor")).click();
        driver.findElement(By.linkText("Mail.ru")).click();
        driver.findElement(By.linkText("Mailigen")).click();
        driver.findElement(By.linkText("MangoOffice")).click();
        driver.findElement(By.linkText("ManyChat")).click();
        driver.findElement(By.linkText("Marquiz")).click();
        driver.findElement(By.linkText("MCN Telecom")).click();
        driver.findElement(By.linkText("MeisterTask")).click();
        driver.findElement(By.linkText("Microsoft Outlook")).click();
        driver.findElement(By.linkText("Moclients")).click();
        driver.findElement(By.linkText("MySQL")).click();
        driver.findElement(By.linkText("myTarget")).click();
        driver.findElement(By.linkText("Nadavi")).click();
        driver.findElement(By.linkText("Nethouse.События")).click();
        driver.findElement(By.linkText("New-Tel")).click();
        driver.findElement(By.linkText("Nextel")).click();
        driver.findElement(By.linkText("OLX")).click();
        driver.findElement(By.linkText("Onlinepbx")).click();
        driver.findElement(By.linkText("Opencart")).click();
        driver.findElement(By.linkText("Pact")).click();
        driver.findElement(By.linkText("Perezvoni")).click();
        driver.findElement(By.linkText("Phonet")).click();
        driver.findElement(By.linkText("Pipedrive")).click();
        driver.findElement(By.linkText("Planfix")).click();
        driver.findElement(By.linkText("PlatformaLP")).click();
        driver.findElement(By.linkText("Portmone")).click();
        driver.findElement(By.linkText("PostgreSQL")).click();
        driver.findElement(By.linkText("PrestaShop")).click();
        driver.findElement(By.linkText("Prom")).click();
        driver.findElement(By.linkText("Puzzlebot")).click();
        driver.findElement(By.linkText("Pyrus")).click();
        driver.findElement(By.linkText("QuizGo")).click();
        driver.findElement(By.linkText("rabota.ua")).click();
        driver.findElement(By.linkText("Rambler")).click();
        driver.findElement(By.linkText("Recreativ")).click();
        driver.findElement(By.linkText("Reply.io")).click();
        driver.findElement(By.linkText("retailCRM")).click();
        driver.findElement(By.linkText("Ringostat")).click();
        driver.findElement(By.linkText("Rozetka")).click();
        driver.findElement(By.linkText("RSS")).click();
        driver.findElement(By.linkText("SaleBot")).click();
        driver.findElement(By.linkText("Salesforce CRM")).click();
        driver.findElement(By.linkText("SendPulse")).click();
        driver.findElement(By.linkText("Senler")).click();
        driver.findElement(By.linkText("Sensei")).click();
        driver.findElement(By.linkText("Slack")).click();
        driver.findElement(By.linkText("Smartcallback")).click();
        driver.findElement(By.linkText("Smartloop")).click();
        driver.findElement(By.linkText("SmartSender")).click();
        driver.findElement(By.linkText("SnatchBot")).click();
        driver.findElement(By.linkText("Stream Telecom")).click();
        driver.findElement(By.linkText("Talk-me")).click();
        driver.findElement(By.linkText("Tap2pay")).click();
        driver.findElement(By.linkText("Taplink")).click();
        driver.findElement(By.linkText("TextBack")).click();
        driver.findElement(By.linkText("Tilda")).click();
        driver.findElement(By.linkText("TimePad")).click();
        driver.findElement(By.linkText("TopVisor")).click();
        driver.findElement(By.linkText("Traffic Light")).click();
        driver.findElement(By.linkText("Trello")).click();
        driver.findElement(By.linkText("TypeForm")).click();
        driver.findElement(By.linkText("U-ON")).click();
        driver.findElement(By.linkText("UIS")).click();
        driver.findElement(By.linkText("UKR.NET")).click();
        driver.findElement(By.linkText("UserEcho")).click();
        driver.findElement(By.linkText("UseResponse")).click();
        driver.findElement(By.linkText("Venyoo")).click();
        driver.findElement(By.linkText("Verbox")).click();
        driver.findElement(By.linkText("WayForPay")).click();
        driver.findElement(By.linkText("Webhooks")).click();
        driver.findElement(By.linkText("Webim")).click();
        driver.findElement(By.linkText("WireCRM")).click();
        driver.findElement(By.linkText("Wix")).click();
        driver.findElement(By.linkText("WooCommerce")).click();
        driver.findElement(By.linkText("Work.ua")).click();
        driver.findElement(By.linkText("Worksection")).click();
        driver.findElement(By.linkText("Wrike")).click();
        driver.findElement(By.linkText("Y-Clients")).click();
        driver.findElement(By.linkText("Yahoo!")).click();
        driver.findElement(By.linkText("Zadarma")).click();
        driver.findElement(By.linkText("Zoho")).click();
        driver.findElement(By.linkText("Бизон 365")).click();
        driver.findElement(By.linkText("Битрикс 24")).click();
        driver.findElement(By.linkText("ВКОНТАКТЕ")).click();
        driver.findElement(By.linkText("Конверсус")).click();
        driver.findElement(By.linkText("Коронавирус COVID-19")).click();
        driver.findElement(By.linkText("Курс валют")).click();
        driver.findElement(By.linkText("Мегаплан")).click();
        driver.findElement(By.linkText("Мой Класс")).click();
        driver.findElement(By.linkText("МойСклад")).click();
        driver.findElement(By.linkText("Новая Почта")).click();
        driver.findElement(By.linkText("Оки-Токи")).click();
        driver.findElement(By.linkText("ПриватБанк (физ лица)")).click();
        driver.findElement(By.linkText("ПриватБанк (юр лица)")).click();
        driver.findElement(By.linkText("РемОнлайн")).click();
        driver.findElement(By.linkText("Телеграм")).click();
        driver.findElement(By.linkText("Телфин")).click();
        driver.findElement(By.linkText("Яндекс Директ")).click();
        driver.findElement(By.linkText("Яндекс Маркет")).click();
        driver.findElement(By.linkText("Яндекс Почта")).click();
        driver.findElement(By.linkText("5. ПРИЕМ данных")).click();
        driver.findElement(By.linkText("1000SMS")).click();
        driver.findElement(By.linkText("ActiveCampaign")).click();
        driver.findElement(By.linkText("AgileCRM")).click();
        driver.findElement(By.linkText("Alfasms.info")).click();
        driver.findElement(By.linkText("AlohaSMS")).click();
        driver.findElement(By.linkText("AlphaSMS")).click();
        driver.findElement(By.linkText("AmoCRM")).click();
        driver.findElement(By.linkText("AOL")).click();
        driver.findElement(By.linkText("Asana")).click();
        driver.findElement(By.linkText("Autopilot")).click();
        driver.findElement(By.linkText("Aweber")).click();
        driver.findElement(By.linkText("BigQuery")).click();
        driver.findElement(By.linkText("BrandSMS")).click();
        driver.findElement(By.linkText("BSG World")).click();
        driver.findElement(By.linkText("BulkSMS")).click();
        driver.findElement(By.linkText("BYTEHAND")).click();
        driver.findElement(By.linkText("ClickSend")).click();
        driver.findElement(By.linkText("CLOFF")).click();
        driver.findElement(By.linkText("Constant Contact")).click();
        driver.findElement(By.linkText("Copper")).click();
        driver.findElement(By.linkText("Creatio")).click();
        driver.findElement(By.linkText("DashaMail")).click();
        driver.findElement(By.linkText("DC Lite")).click();
        driver.findElement(By.linkText("Ecwid")).click();
        driver.findElement(By.linkText("EnvyCRM")).click();
        driver.findElement(By.linkText("ePochta")).click();
        driver.findElement(By.linkText("eSputnik")).click();
        driver.findElement(By.linkText("Estismail")).click();
        driver.findElement(By.linkText("EVE.calls")).click();
        driver.findElement(By.linkText("ExpertSender")).click();
        driver.findElement(By.linkText("Facebook")).click();
        driver.findElement(By.linkText("Falconsender")).click();
        driver.findElement(By.linkText("Feedgee")).click();
        driver.findElement(By.linkText("FreshOffice")).click();
        driver.findElement(By.linkText("G-mail")).click();
        driver.findElement(By.linkText("GetCourse")).click();
        driver.findElement(By.linkText("GetResponse")).click();
        driver.findElement(By.linkText("Google Ads")).click();
        driver.findElement(By.linkText("Google Analytics")).click();
        driver.findElement(By.linkText("Google Calendar")).click();
        driver.findElement(By.linkText("Google Contacts")).click();
        driver.findElement(By.linkText("Google Sheets")).click();
        driver.findElement(By.linkText("GREENSMS")).click();
        driver.findElement(By.linkText("Hubspot")).click();
        driver.findElement(By.linkText("iCloud")).click();
        driver.findElement(By.linkText("Imobis")).click();
        driver.findElement(By.linkText("INBOX.LV")).click();
        driver.findElement(By.linkText("InSales")).click();
        driver.findElement(By.linkText("Intel Telecom")).click();
        driver.findElement(By.linkText("Jira Service Desk")).click();
        driver.findElement(By.linkText("Jira Software Cloud")).click();
        driver.findElement(By.linkText("Justin")).click();
        driver.findElement(By.linkText("Kupisms")).click();
        driver.findElement(By.linkText("Lamoda")).click();
        driver.findElement(By.linkText("LetsAds")).click();
        driver.findElement(By.linkText("LiqPay")).click();
        driver.findElement(By.linkText("LpCRM")).click();
        driver.findElement(By.linkText("Mail.ru")).click();
        driver.findElement(By.linkText("Mail365")).click();
        driver.findElement(By.linkText("MailChimp")).click();
        driver.findElement(By.linkText("MailerLite")).click();
        driver.findElement(By.linkText("Mailganer")).click();
        driver.findElement(By.linkText("Mailo Post")).click();
        driver.findElement(By.linkText("MassDelivery")).click();
        driver.findElement(By.linkText("MeisterTask")).click();
        driver.findElement(By.linkText("Messedo")).click();
        driver.findElement(By.linkText("Microsoft Outlook")).click();
        driver.findElement(By.linkText("MIRSMS.RU")).click();
        driver.findElement(By.linkText("Mobizon")).click();
        driver.findElement(By.linkText("MySQL")).click();
        driver.findElement(By.linkText("NotiSend")).click();
        driver.findElement(By.linkText("Odoo")).click();
        driver.findElement(By.linkText("OLX")).click();
        driver.findElement(By.linkText("Omnicell")).click();
        driver.findElement(By.linkText("Online-sms.pro")).click();
        driver.findElement(By.linkText("Opencart")).click();
        driver.findElement(By.linkText("P1SMS")).click();
        driver.findElement(By.linkText("Pipedrive")).click();
        driver.findElement(By.linkText("Planfix")).click();
        driver.findElement(By.linkText("Portmone")).click();
        driver.findElement(By.linkText("PostgreSQL")).click();
        driver.findElement(By.linkText("PrestaShop")).click();
        driver.findElement(By.linkText("Prom")).click();
        driver.findElement(By.linkText("Prostor SMS")).click();
        driver.findElement(By.linkText("ProstoSMS")).click();
        driver.findElement(By.linkText("PushSMS")).click();
        driver.findElement(By.linkText("Pyrus")).click();
        driver.findElement(By.linkText("Rambler")).click();
        driver.findElement(By.linkText("RamexCRM")).click();
        driver.findElement(By.linkText("RedSMS")).click();
        driver.findElement(By.linkText("Reply.io")).click();
        driver.findElement(By.linkText("retailCRM")).click();
        driver.findElement(By.linkText("RocketSMS")).click();
        driver.findElement(By.linkText("Rozetka")).click();
        driver.findElement(By.linkText("Salesforce CRM")).click();
        driver.findElement(By.linkText("SendGrid")).click();
        driver.findElement(By.linkText("Sendinblue")).click();
        driver.findElement(By.linkText("SendPulse")).click();
        driver.findElement(By.linkText("SendSay")).click();
        driver.findElement(By.linkText("SigmaSMS")).click();
        driver.findElement(By.linkText("SkySMS")).click();
        driver.findElement(By.linkText("Slack")).click();
        driver.findElement(By.linkText("SMS Aero")).click();
        driver.findElement(By.linkText("SMS Club")).click();
        driver.findElement(By.linkText("SMS Gorod")).click();
        driver.findElement(By.linkText("SMS Traffic")).click();
        driver.findElement(By.linkText("SMS Курьер")).click();
        driver.findElement(By.linkText("SMS Украина")).click();
        driver.findElement(By.linkText("SMS-fly")).click();
        driver.findElement(By.linkText("SMS-Manager")).click();
        driver.findElement(By.linkText("SMS-Ассистент")).click();
        driver.findElement(By.linkText("SMS-Центр")).click();
        driver.findElement(By.linkText("SMS.BY")).click();
        driver.findElement(By.linkText("SMS.ru")).click();
        driver.findElement(By.linkText("Sms.su")).click();
        driver.findElement(By.linkText("SMS4B")).click();
        driver.findElement(By.linkText("SmsBliss")).click();
        driver.findElement(By.linkText("SMSfeedback")).click();
        driver.findElement(By.linkText("SMSGold")).click();
        driver.findElement(By.linkText("SMSimple")).click();
        driver.findElement(By.linkText("SMSint")).click();
        driver.findElement(By.linkText("SMSP.BY")).click();
        driver.findElement(By.linkText("SMSPILOT")).click();
        driver.findElement(By.linkText("SMSprofi")).click();
        driver.findElement(By.linkText("SMStraf")).click();
        driver.findElement(By.linkText("SMTP")).click();
        driver.findElement(By.linkText("SprintSMS")).click();
        driver.findElement(By.linkText("Ssms.su")).click();
        driver.findElement(By.linkText("StartSend")).click();
        driver.findElement(By.linkText("SvitSMS")).click();
        driver.findElement(By.linkText("TargetSMS")).click();
        driver.findElement(By.linkText("TeraSMS")).click();
        driver.findElement(By.linkText("TopVisor")).click();
        driver.findElement(By.linkText("Traffic Light")).click();
        driver.findElement(By.linkText("Trello")).click();
        driver.findElement(By.linkText("TurboSMS")).click();
        driver.findElement(By.linkText("Twilio")).click();
        driver.findElement(By.linkText("U-ON")).click();
        driver.findElement(By.linkText("UKR.NET")).click();
        driver.findElement(By.linkText("Unipost")).click();
        driver.findElement(By.linkText("UniSender")).click();
        driver.findElement(By.linkText("VerticalResponse")).click();
        driver.findElement(By.linkText("Viber")).click();
        driver.findElement(By.linkText("WebSMS")).click();
        driver.findElement(By.linkText("WHATSAPP (через партнера AceBot)")).click();
        driver.findElement(By.linkText("WireCRM")).click();
        driver.findElement(By.linkText("Worksection")).click();
        driver.findElement(By.linkText("Wrike")).click();
        driver.findElement(By.linkText("y-clients")).click();
        driver.findElement(By.linkText("Yahoo!")).click();
        driver.findElement(By.linkText("Zadarma")).click();
        driver.findElement(By.linkText("Zoho")).click();
        driver.findElement(By.linkText("Бизон 365")).click();
        driver.findElement(By.linkText("Битрикс 24")).click();
        driver.findElement(By.linkText("ВКонтакте")).click();
        driver.findElement(By.linkText("Мегаплан")).click();
        driver.findElement(By.linkText("Мир-смс.рф")).click();
        driver.findElement(By.linkText("Мой Класс")).click();
        driver.findElement(By.linkText("МойСклад")).click();
        driver.findElement(By.linkText("Новая Почта")).click();
        driver.findElement(By.linkText("РемОнлайн")).click();
        driver.findElement(By.linkText("СМС Дисконт")).click();
        driver.findElement(By.linkText("СМС Услуги")).click();
        driver.findElement(By.linkText("Телеграм")).click();
        driver.findElement(By.linkText("Яндекс Метрика")).click();
        driver.findElement(By.linkText("Яндекс Почта")).click();
        driver.findElement(By.linkText("6. МАТЕМАТИЧЕСКИЕ операции")).click();
        driver.findElement(By.linkText("7. ФИЛЬТР данных")).click();
        driver.findElement(By.linkText("8. ФОРМАТИРОВАНИЕ")).click();
        driver.findElement(By.linkText("9. ПОИСК данных")).click();
        driver.findElement(By.linkText("Курс валют")).click();
        driver.findElement(By.linkText("Новая Почта")).click();
        driver.findElement(By.linkText("О сервисе")).click();
        driver.findElement(By.linkText("Партнерский кабинет")).click();
        driver.findElement(By.linkText("Рекламные материалы")).click();
        driver.findElement(By.linkText("Поддержка")).click();
        driver.findElement(By.linkText("Тарифы и Оплата")).click();
        driver.findElement(By.linkText("ШАБЛОНЫ интеграций")).click();
        driver.findElement(By.linkText("Facebook - Google Sheets")).click();
        driver.findElement(By.linkText("Facebook - Битрикс 24")).click();
        driver.findElement(By.linkText("Facebook - Телеграм")).click();
        driver.findElement(By.linkText("HotLine - Google Sheets")).click();
        driver.findElement(By.linkText("Rozetka - Google Sheets")).click();
        driver.findElement(By.linkText("Интеграции сервисов по API")).click();
        driver.findElement(By.linkText("Admitad")).click();
        driver.findElement(By.linkText("Admitad - Google Sheets")).click();
        driver.findElement(By.linkText("AlphaSMS")).click();
        driver.findElement(By.linkText("Facebook - AlphaSMS")).click();
        driver.findElement(By.linkText("Google Sheets - AlphaSMS")).click();
        driver.findElement(By.linkText("OpenCart - AlphaSMS")).click();
        driver.findElement(By.linkText("AmoCRM")).click();
        driver.findElement(By.linkText("AmoCRM - Телеграм")).click();
        driver.findElement(By.linkText("Binotel")).click();
        driver.findElement(By.linkText("CallBackHunter")).click();
        driver.findElement(By.linkText("Contact Form 7")).click();
        driver.findElement(By.linkText("Envybox")).click();
        driver.findElement(By.linkText("eSputnik")).click();
        driver.findElement(By.linkText("Facebook")).click();
        driver.findElement(By.linkText("Facebook - Google Sheets")).click();
        driver.findElement(By.linkText("Facebook - Битрикс 24")).click();
        driver.findElement(By.linkText("Facebook - Телеграм")).click();
        driver.findElement(By.linkText("Google Sheets")).click();
        driver.findElement(By.linkText("Google Sheets - Битрикс 24")).click();
        driver.findElement(By.linkText("Google Sheets - Телеграм")).click();
        driver.findElement(By.linkText("Horoshop")).click();
        driver.findElement(By.linkText("HotLine")).click();
        driver.findElement(By.linkText("JivoSite")).click();
        driver.findElement(By.linkText("Livetex")).click();
        driver.findElement(By.linkText("LPGenerator")).click();
        driver.findElement(By.linkText("MonsterLeads")).click();
        driver.findElement(By.linkText("OpenCart")).click();
        driver.findElement(By.linkText("OpenCart - AmoCRM")).click();
        driver.findElement(By.linkText("OpenCart - Google Sheets")).click();
        driver.findElement(By.linkText("OpenCart - Битрикс 24")).click();
        driver.findElement(By.linkText("OpenCart - Телеграм")).click();
        driver.findElement(By.linkText("Phonet")).click();
        driver.findElement(By.linkText("Prom")).click();
        driver.findElement(By.linkText("Prom - AmoCRM")).click();
        driver.findElement(By.linkText("Prom - Битрикс 24")).click();
        driver.findElement(By.linkText("Rozetka")).click();
        driver.findElement(By.linkText("Rozetka - AmoCRM")).click();
        driver.findElement(By.linkText("Rozetka - Google Sheets")).click();
        driver.findElement(By.linkText("Rozetka - Битрикс 24")).click();
        driver.findElement(By.linkText("SellAction")).click();
        driver.findElement(By.linkText("SendPulse")).click();
        driver.findElement(By.linkText("Stream Telecom")).click();
        driver.findElement(By.linkText("Tilda")).click();
        driver.findElement(By.linkText("TurboSMS")).click();
        driver.findElement(By.linkText("UniSender")).click();
        driver.findElement(By.linkText("WooCommerce")).click();
        driver.findElement(By.linkText("Битрикс 24")).click();
        driver.findElement(By.linkText("Битрикс 24 - Телеграм")).click();
        driver.findElement(By.linkText("Телеграм")).click();
        driver.findElement(By.linkText("Чат Боты")).click();
    }

    @Test
    public void testConnectionType1Selected() throws Exception {
        driver.manage().window().setPosition(new Point(0,0));
        driver.manage().window().setSize(new Dimension(1024,768));
        driver.get("https://apix-drive.com/ru");
        driver.findElement(By.linkText("Вход")).click();
        driver.findElement(By.name("login")).click();
        driver.findElement(By.name("login")).clear();
        driver.findElement(By.name("login")).sendKeys("alextesting23@gmail.com");
        driver.findElement(By.name("pass")).clear();
        driver.findElement(By.name("pass")).sendKeys("123456gg");
        driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        driver.findElement(By.linkText("test auto")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Active Chat");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Active Chat")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("ActiveCampaign");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("ActiveCampaign")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Admitad");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Admitad")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Agile CRM");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Agile CRM")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Aimylogic");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Aimylogic")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Alloka");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Alloka")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AmoCRM");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AmoCRM")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AOL");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AOL")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Asana");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Asana")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BigQuery");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BigQuery")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Binotel");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Binotel")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Bloxy");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Bloxy")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BotHelp");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BotHelp")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Botmother");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Botmother")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Bpium");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Bpium")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("CallbackHunter");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("CallbackHunter")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Callcpa");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Callcpa")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Callibri");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Callibri")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("CallKeeper");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
   // Connecting type2
        driver.findElement(By.linkText("+")).click();
        driver.findElement(By.linkText("Добавить ПРИЕМНИК данных")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("1000SMS");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("1000SMS")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("ActiveCampaign");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("ActiveCampaign")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Agile CRM");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Agile CRM")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AlfaSMS");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AlfaSMS")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AlohaSMS");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AlohaSMS")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AlphaSMS");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AlphaSMS")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AmoCRM");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AmoCRM")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("AOL");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("AOL")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Asana");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Asana")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Autopilot");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Autopilot")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Aweber");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("Aweber")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BigQuery");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BigQuery")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BrandSMS");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BrandSMS")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BSG world");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BSG world")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BulkSMS");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BulkSMS")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("BYTEHAND");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BYTEHAND")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("BYTEHAND")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("ClickSend");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("ClickSend")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("CLOFF");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.linkText("CLOFF")).click();
        driver.findElement(By.name("settings[system_id]")).click();
        new Select(driver.findElement(By.name("settings[system_id]"))).selectByVisibleText("Constant Contact");
        driver.findElement(By.name("settings[system_id]")).click();
        driver.findElement(By.name("save_settings_submit")).click();
        driver.findElement(By.xpath("//div[@id='main_site_body']/div/div[4]/div/div[6]/div/div[2]/a/span")).click();
        driver.findElement(By.xpath("(//a[contains(text(),'Главная')])[2]")).click();
        driver.findElement(By.xpath("//div[@id='user_menu']/div[2]/div")).click();
        driver.findElement(By.linkText("Выход")).click();
    }

    @After
    public void close() {
        System.out.println("Тест успешно окончен.");
        driver.quit();
    }
}
